name: rigolaz_2
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.2
  firebase_auth: ^0.14.0+5
  cloud_firestore: ^0.13.0+1
  firebase_core: ^0.4.2+1
  provider: ^3.1.0
  flutter_spinkit: ^4.1.2


    

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:

  uses-material-design: true

  

  assets:
    - images/logo_rigolaz.png
    - images/logo.PNG
    - images/page1.png
    - images/page2.png
    - images/page3.png
    - images/cb.png
    - images/om.png
    - images/mtn.png
    - images/nexttel.png
    

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: Actor
       fonts:
         - asset: fonts/Actor-Regular.ttf
     - family: YesevaOne
       fonts:
         - asset: fonts/YesevaOne-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
